# Generated by Django 4.1.7 on 2023-03-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('-created',), 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
